on: [push, pull_request]

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run cargo test
        run: |
          cargo test --verbose
